# Site settings
title: BSG Unified Rulebook
email: jbiatek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A unified rulebook for all of Battlestar Galactica and its expansions. 
baseurl: "BSGRulebook/" # the subpath of your site, e.g. /blog/
url: "http://jbiatek.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
